name: huellasdelfos
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  connectivity_plus: ^6.1.0
  sqflite: ^2.4.1
  path_provider: ^2.1.4
  path: ^1.9.0
  image_picker: ^1.1.2
  flutter_sound: ^9.6.0
  signature: ^5.5.0
  wakelock_plus: ^1.2.8
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  supabase_flutter: ^2.8.0
  file_picker: ^8.0.6
  geolocator: ^13.0.2
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/data/precargado.csv

